const actionTypes = {
    ADD_PET_REQUEST_START: 'ADD_PET_REQUEST_START',
    ADD_PET_REQUEST_SUCCESS: 'ADD_PET_REQUEST_SUCCESS',
    ADD_PET_REQUEST_FAILURE: 'ADD_PET_REQUEST_FAILURE',
    SET_PET_ID: 'SET_PET_ID',
    CLEAR_PET_DATA: 'CLEAR_PET_DATA',
};


export default actionTypes;
