const actionTypes = {
    GET_ALL_PETS_REQUEST_START: 'GET_ALL_PETS_REQUEST_START',
    GET_ALL_PETS_REQUEST_SUCCESS: 'GET_ALL_PETS_REQUEST_SUCCESS',
    GET_ALL_PETS_REQUEST_FAILURE: 'GET_ALL_PETS_REQUEST_FAILURE',
    CLEAR_PET_COLLECTION_DATA: 'CLEAR_PET_COLLECTION_DATA',
};

export default actionTypes;
