const actionTypes = {
    CREATE_ADD_USER_REQUEST_START: 'CREATE_ADD_USER_REQUEST_START',
    CREATE_ADD_USER_REQUEST_SUCCESS: 'CREATE_ADD_USER_REQUEST_SUCCESS',
    CREATE_ADD_USER_REQUEST_FAILURE: 'CREATE_ADD_USER_REQUEST_FAILURE',

    SET_USER_ID: 'SET_USER_ID',
    CLEAR_USER_DATA: 'CLEAR_USER_DATA',
};


export default actionTypes;
